# Generated by Django 5.2.12 on 2026-04-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payloads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('status_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('service_group', models.CharField(choices=[('mobility', 'Mobility'), ('delivery', 'Delivery'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_bucket', models.CharField(blank=True, max_length=20, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_leg_count', models.PositiveIntegerField(default=0)),
                ('is_pool_type', models.BooleanField(default=False)),
                ('is_surge', models.BooleanField(default=False)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('dropoff_address', models.TextField(blank=True, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earnings_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('earnings_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.OneToOneField(limit_choices_to={'payload_type': 'detail'}, on_delete=django.db.models.deletion.CASCADE, related_name='uber_trip', to='payloads.rawpayload')),
            ],
            options={
                'verbose_name': 'Uber Trip',
                'verbose_name_plural': 'Uber Trips',
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
    ]
