# Generated by Django 5.2.13 on 2026-04-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubertrip',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='dropoff_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='pickup_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='status_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='time_bucket',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
