# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_ubertrip_day_of_week_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("fuel", "Gasolina"), ("maintenance", "Mantenimiento"), ("tolls", "Peajes"), ("taxes", "Impuestos"), ("verification", "Verificacion vehicular"), ("insurance", "Seguro"), ("other", "Otro")], default="other", max_length=30)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Operating Cost",
                "verbose_name_plural": "Operating Costs",
                "ordering": ["-cost_date", "-created_at"],
            },
        ),
    ]
