# Generated by Django 5.2.12 on 2026-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_type', models.CharField(choices=[('activity', 'Activity'), ('detail', 'Detail')], max_length=20)),
                ('source_name', models.CharField(blank=True, help_text='Nombre del archivo o lote de origen', max_length=255, null=True)),
                ('external_uuid', models.CharField(blank=True, db_index=True, help_text='UUID o identificador externo del payload', max_length=100, null=True)),
                ('raw_data', models.JSONField(help_text='Payload crudo almacenado en formato JSON')),
                ('ingestion_status', models.CharField(choices=[('received', 'Received'), ('saved', 'Saved'), ('failed', 'Failed')], default='saved', max_length=20)),
                ('ingestion_error', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raw_payloads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payload_type', 'processing_status'], name='raw_payload_payload_bf85e5_idx'), models.Index(fields=['payload_type', 'external_uuid'], name='raw_payload_payload_6fd8e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('payload_type', 'external_uuid'), name='unique_payload_type_external_uuid')],
            },
        ),
    ]
